### Получить все валюты
GET http://localhost:8080/currencies

### Получить конкретную валюту USD (200)
GET http://localhost:8080/currency/USD

### Попытка получить несуществующую валюту (404)
GET http://localhost:8080/currency/ZZZ

### Попытка получить валюту в нижнем регистре (200)
GET http://localhost:8080/currency/usd

### Попытка получить некорретный формат валюты (400)
GET http://localhost:8080/currency/123

### Отсутствие кода валюты (400)
GET http://localhost:8080/currency/

### Попытка добавить валюту с пустым полем (400)
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

name=British Pound&code=&sign=£

### Попытка добавить уже существующую валюту (409)
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

name=Euro&code=EUR&sign=€

### Добавляем новую валюту RUB (201)
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

name=Russian Ruble&code=RUB&sign=₽

### Попытка добавить валюту с sign > 3 (400)
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

name=Sign&code=RIP&sign=META

### Попытка добавить валюту с пустым name (400)
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

name=  &code=BYC&sign=#

### Попытка добавить валюту с пустым code (400)
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

name=ABC&code=   &sign=#

### Попытка добавить валюту с пустым sign (400)
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

name=AC&code=DC &sign=