### Получить все обменные курсы
GET http://localhost:8080/exchangeRates

### Получить обменный курс по опреденным валютам (200):
GET http://localhost:8080/exchangeRate/USDRUB

### Попытка получить несуществующий обменный курс (404):
GET http://localhost:8080/exchangeRate/RUBUAH

### Проверка отсутсвия валидного кода запроса (400):
GET http://localhost:8080/exchangeRate/XANDERGI

### Проверка отсутсвия валидного кода запроса (400):
GET http://localhost:8080/exchangeRate/X1NDE4

### Проверка отсутсвия валидного кода запроса (400):
GET http://localhost:8080/exchangeRate

### Проверка отсутсвия валидного кода запроса (400):
GET http://localhost:8080/exchangeRate/null

### Успешное добавние обменной пары (201):
POST http://localhost:8080/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=EUR&targetCurrencyCode=RUB&rate=92.02

### Ошибка валидации: отсутствует поле rate (400):
POST http://localhost:8080/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=USD&targetCurrencyCode=EUR

### Ошибка: некорретный код валюты в теле запроса (400):
POST http://localhost:8080/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=XI&targetCurrencyCode=RC&rate=666.666

### Ошибка: одна(или обе) из валют не существует (404)
POST http://localhost:8080/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=XGI&targetCurrencyCode=RPC&rate=666.666

### Проверка на уже существующу обменную пару в БД (409):
POST http://localhost:8080/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=USD&targetCurrencyCode=RUB&rate=77.23

### Проверка на одинаковые коды валют (400):
POST http://localhost:8080/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=RUB&targetCurrencyCode=RUB&rate=1

### Проверка на отрицательное значение rate (400):
POST http://localhost:8080/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=USD&targetCurrencyCode=RUB&rate=-1

### Успешное изменение значения обменной пары (200):
PATCH http://localhost:8080/exchangeRate/USDRUB
Content-Type: application/x-www-form-urlencoded

rate=77.43

### Проверка отсутсвия валидного кода запроса (400):
PATCH http://localhost:8080/exchangeRate/USD
Content-Type: application/x-www-form-urlencoded

rate=77.43

### Проверка отсутсвия валидного кода запроса (400):
PATCH http://localhost:8080/exchangeRate/
Content-Type: application/x-www-form-urlencoded

rate=77.43

### Попытка отправить пустой body (400):
PATCH http://localhost:8080/exchangeRate/USDRUB
Content-Type: application/x-www-form-urlencoded


### Попытка отправить корректный body но с пустым значением (400):
PATCH http://localhost:8080/exchangeRate/USDRUB
Content-Type: application/x-www-form-urlencoded

rate=

### Попытка отправить корректный body но с null (400):
PATCH http://localhost:8080/exchangeRate/USDRUB
Content-Type: application/x-www-form-urlencoded

rate=null

### Попытка отправить корректный body но с "," в значении (400):
PATCH http://localhost:8080/exchangeRate/USDRUB
Content-Type: application/x-www-form-urlencoded

rate=77,43

### Попытка отправить корректный body но с отрицательным значением (400):
PATCH http://localhost:8080/exchangeRate/USDRUB
Content-Type: application/x-www-form-urlencoded

rate=-77.43

### Попытка отправить некорректный body (400):
PATCH http://localhost:8080/exchangeRate/USDRUB
Content-Type: application/x-www-form-urlencoded

amount=47

### Попытка отправить корректный body но с некорректным типом данных (400):
PATCH http://localhost:8080/exchangeRate/USDRUB
Content-Type: application/x-www-form-urlencoded

rate=бесплатно?

### Не существующая обменная пара (404):
PATCH http://localhost:8080/exchangeRate/XYZABC
Content-Type: application/x-www-form-urlencoded

rate=666.666

### Успешной прямой обмен валюты (200):
GET  http://localhost:8080/exchange?from=USD&to=RUB&amount=10
Content-Type: application/x-www-form-urlencoded

### Успешной обратный обмен валюты (200):
GET  http://localhost:8080/exchange?from=RUB&to=USD&amount=774.30
Content-Type: application/x-www-form-urlencoded

### Успешный кросс-курс RUB-UAH (200):
GET http://localhost:8080/exchange?from=RUB&to=UAH&amount=774.30

### Успешный кросс-курс RUB-EUR (200):
GET http://localhost:8080/exchange?from=RUB&to=EUR&amount=774.30

### Обменная пара не найдена (404):
GET http://localhost:8080/exchange?from=RUB&to=INR&amount=774.30

### Попытка обмена одинаковой пары валют (400):
GET http://localhost:8080/exchange?from=RUB&to=RUB&amount=137.69

### Попытка обмена при пустых значениях (400):
GET http://localhost:8080/exchange?from=&to=&amount=137.69

### Попытка обмена при пустых значениях (400):
GET http://localhost:8080/exchange?from=&to=&amount=137.69

### Попытка обмена при amount = infitiny(400):
GET http://localhost:8080/exchange?from=RUB&to=USD&amount=infinity

### Попытка обмена при amount < 0 (400):
GET http://localhost:8080/exchange?from=RUB&to=USD&amount=-123

### Попытка обмена при amount = 0 (400):
GET http://localhost:8080/exchange?from=RUB&to=USD&amount=0

### Попытка обмена, когда amount это текст (400):
GET http://localhost:8080/exchange?from=USD&to=RUB&amount=ten

### Попытка обмена с некорректным разделителем дроби (400):
GET http://localhost:8080/exchange?from=USD&to=RUB&amount=10,5

### Некорректный код валюты (слишком короткий) (400):
GET http://localhost:8080/exchange?from=US&to=RUB&amount=10

### Некорректный код валюты (слишком длинный) (400):
GET http://localhost:8080/exchange?from=USDT&to=TRX&amount=10

### Отсутствует параметр amount (400):
GET http://localhost:8080/exchange?from=USD&to=RUB

### Отсутствует параметр from (400):
GET http://localhost:8080/exchange?to=RUB&amount=10